# Flexget Configuration File
# http://www.flexget.com
# Created by: Luis Checa <edhaker13@gmail.com>
# Inspired by the configuration file from atlanta800's git
# https://github.com/atlanta800/dotfiles/blob/master/flexget/config.yml
# and other examples/information from the wiki
# http://flexget.com/wiki/Plugins

# password, api keys others sensitive info. {{ secrets.example.password }}
secrets: secrets.yml

templates:
  # This template will be applied to all tasks unless no_global preset is included
  global:
    # Make sure there's at least 5GB free space
    free_space:
      path: /mnt/usb/
      space: 5000
    # Make filename Windows safe (for samba)
    pathscrub: windows
    # Reject private torrents since I'm not on any private trackers for now
    private_torrents: no
    # Scrub the torrent for any data that'll prevent the torrent from working
    torrent_scrub: on
    # Make a rss with successful entries for ease of access
    make_rss:
      file: /mnt/usb/flexget.rss
      encoding: utf-8
    # Notifies me via email, always avaible on some device
    email:
      from: '{{ secrets.email.from }}'
      to: '{{ secrets.email.to }}'
      template: failed
      smtp_host: '{{ secrets.email.host }}'
      smtp_port: 465
      smtp_ssl: yes
      smtp_username: '{{ secrets.email.username }}'
      smtp_password: '{{ secrets.email.password }}'
    # 1080p is a waste of bandwitdh, most releases aren't good quality 1080p
    quality: 720p
    # Enable torrent output
    transmission:
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      host: '{{ secrets.transmission.host }}'
      main_file_only: yes
      magnetization_timeout: 20
      #include_subs: yes
      rename_like_files: yes
    set:
      # Series name without non-ascii characters
      series_name: '{{ series_name|re_replace("[^\x00-\x7F]"," ") }}'
      # Path results /mnt/usb/anime/SeriesName/
      path: '/mnt/usb/{{ task|replace("search_","") }}/{{ series_name }}'

  # This template has all the anime related settings
  anime:
    # RSS feeds for anime, shows only english anime and non remakes
    rss:
      url: 'http://www.nyaa.se/?page=rss&cats=1_37&filter=2'
      all_entries: no
    assume_quality: 720p
    # Set filename, output would be Series Name 01.mkv
    set:
      content_filename: '{{ series_name }} {{ series_id|pad(2) }}'
    # Set some reasonable size limits also ensures no packs
    content_size:
      max: 1000
      min: 20
   # Prevent from downloading files that are downloading(ed)
    exists_series:
      - '/mnt/usb/downloads/'
      - '/mnt/usb/anime/'
    # Filter any raws, OST , manga that may have fallen through the rss filters
    regexp:
      reject:
        -  raw|ost|manga|soundtrack|song|\[ED\]|\[OP\]|patch: { from: title }
    # List of shows I want to see, from MAL
    configure_series:
      from:
        myanimelist:
          username: '{{ secrets.mal_username }}'
    # Add alternate names
    series:
      - 'Diamond no Ace: Second Season':
          alternate_name:
            - Ace of the Diamond ~Second Season~
            - Ace of Diamond S2
      - 'Ansatsu Kyoushitsu (TV)':
          alternate_name: Assasination Classroom S2
      - Haikyuu!! Second Season:
          alternate_name: Haikyuu!! S2
  # Template for all TV related settings and list of shows
  tv:
    # List of feeds to use already filtered for shows and 720p
    rss:
      url: 'http://showrss.info/rss.php?user_id=118811'
      all_entries: no
    # Feed already filtered at creation
    all_series: yes
    # Check for already downloaded or downloading
    exists_series:
      - '/mnt/usb/downloads/'
      - '/mnt/usb/tv/'
    # Add show to subtitle download queue
    subtitle_queue:
      action: add
      path: '{{ path }}'
      alternate_path: '{{ path }}/{{ content_filename }}'
    # Mark accepted entries to trakt collection
    trakt_add:
      username: '{{ secrets.trakt.username }}'
      password: '{{ secrets.trakt.password }}'
      list: collection
tasks:
  anime:
    template: anime
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Moar Animu!!
  tv:
    template: tv
    # Notifies using Notify My Android, already paid for premium so not changing.
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: New TV Episode
  search_anime:
    template: anime
    no_entries_ok: yes
    urlrewrite_search:
      - nyaa:
          filter: filter remakes
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Found Animu!
  search_tv:
    template: tv
    no_entries_ok: yes
    urlrewrite_search:
      - piratebay:
          category: 208
          sort_by: seeds
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Found Shows!
  search_subs:
    template: no_global
    no_entries_ok: yes
    inputs:
      - subtitle_queue: emit
      - find:
          path:
            - '/mnt/usb/tv'
          regexp: '.*\.(mkv|mp4)$'
          recursive: yes
    disable: [retry_failed]
    seen: local
    all_series: yes
    subliminal:
      languages:
        - eng
  maintenance:
    template: no_global
    no_entries_ok: yes
    disable: [details]
    # Clean completed torrents
    clean_transmission:
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      host: '{{ secrets.transmission.host }}'
      finished_for: 12 hours

schedules:
  - tasks: [anime]
    interval: { minutes: 30 }

  - tasks: [tv]
    schedule:
      minute: 15,25,45
      hour: 1,4,5,7,18,23

  - tasks: [search_anime, search_tv, search_subs]
    interval: { hours: 6 }

  - tasks: [maintenance]
    interval: { hours: 24 }
