# Flexget Configuration File
# http://www.flexget.com
# Created by: Luis Checa <edhaker13@gmail.com>
# Inspired by the configuration file from atlanta800's git
# https://github.com/atlanta800/dotfiles/blob/master/flexget/config.yml
# and other examples/information from the wiki
# http://flexget.com/wiki/Plugins

# password, api keys others sensitive info. {{ secrets.example.password }}
secrets: secrets.yml

templates:
  # This template will be applied to all tasks unless no_global preset is included
  global:
    # Make sure there's at least 5GB free space
    free_space:
      path: /mnt/usb/
      space: 5000
    # Make filename Windows Safe (for samba)
    pathscrub: windows
    # Reject magnets since they don't allow scraping, size or content filtering
    magnets: no
    # Reject private torrents since I'm not on any private trackers for now
    private_torrents: no
    # Some torrents links are invalid https
    # verify_ssl_certificates: no
    # Scrub the torrent for any data that'll prevent the torrent from working
    torrent_scrub: on
    # Make a rss with successful entries for ease of access
    make_rss:
      file: /mnt/usb/flexget.rss
      days: -1
      items: -1
      encoding: utf-8
    # Notifies me via email, sometimes I just forget or it doesn't show up on NMA
    email:
      from: '{{ secrets.email.from }}'
      to: '{{ secrets.email.to }}'
      template: cifs_server
      smtp_host: '{{ secrets.email.host }}'
      smtp_port: 465
      smtp_ssl: yes
      smtp_username: '{{ secrets.email.username }}'
      smtp_password: '{{ secrets.email.password }}'

    # Set some reasonable size limits also ensures no packs
    content_size:
      max: 5000
      min: 20
    # 1080p is a waste of bandwitdh, most releases aren't good quality 1080p
    quality: 720p
    # Reject common torrent trash
    regexp:
      reject:
        # Block any subbed/dubbed/etc videos
       # - (s|d)ub(s|bed)?\b: {from: title}
        # Block series, only accept one at a time
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        # I don't have any 3D displays
        - \b3-?D\b: {from: title}
        # I've gotten a few trailers that matched as movies. VERY annoying
        - \btrailer\b: {from: title}
        # The following are poor quality types that somehow got through the quality
        - \bR5\b: {from: title}
        # usually due to the title including a keyword like "720p" as well
        - \bWEBSCR\b: {from: title}
        # bad quality sources, just in case
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - \bRAW\b: {from: title}
        # Reject rar/packs/password
        - \.rar|\.r\d\d|password.txt|\.zip
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      tokyotosho.info: 15 seconds
      nyaa.se: 15 seconds
      showrss.info: 15 seconds
    # Enable deluge output
    transmission:
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      host: '{{ secrets.transmission.host }}'
      # main_file_only: yes
      include_subs: yes
      rename_like_files: yes
    set:
      # Path results /mnt/usb/anime/ShowName/
      path: /mnt/usb/{{task}}/{{series_name}}
      # Output would be -> Show Name 02 [720p10bit].mkv
      content_filename: '{{ series_name }} {{ series_id|pad(2) }} [{{ quality }}]'

  # This template has all the anime related settings
  anime:
    # RSS feeds for Anime, force ascii: the japanese characters can cause errors
    inputs:
      # Shows only english anime and is sorted by seeds
      - rss: { url: 'http://www.nyaa.se/?page=rss&cats=1_37&filter=2', silent: yes, ascii: yes }
      # Filtered for anime only
      - rss: { url: 'http://tokyotosho.info/rss.php?filter=1', silent: yes, ascii: yes }
    # Some groups don't put qualities in their filename (yes you, horriblesubs)
    assume_quality: 720p
    # Prevent from downloading files that are downloading(ed)
    exists_series:
      - '/mnt/usb/downloads/'
      - '/mnt/usb/anime/'
    # Filter any raws, OST , manga that may have fallen through the rss filters
    regexp:
      reject:
        -  raw | ost | manga | soundtrack | song |\[ED\]|\[OP\]|(4|7)00(p|x): {from: title}
    # List of shows I want to see, from MAL
    configure_series:
      settings:
        identified_by: sequence
      from:
        myanimelist:
          username: '{{ secrets.mal_username }}'
  # template for all TV related settings and list of shows, just for show now
  tv:
    # List of feeds to use already filtered for shows and 720p
    inputs:
      - rss: { url: 'http://showrss.info/rss.php?user_id=118811&hd=1&proper=0', silent: yes }
    # Feed already filtered at creation
    accept_all: yes
    # Check for already downloaded or downloading
    exists_series:
      - '/mnt/usb/downloads/'
      - '/mnt/usb/tv/'
    # Add show to subtitle download queue
    subtitle_queue:
      action: add
      path: '{{ path }}'
    # List of shows I want to see, from trakt
    #configure_series:
      #from:
        #trakt_list:
          #username: '{{ secrets.trakt.username }}'
          #password: '{{ secrets.trakt.password }}'
          #list: watchlist
          #type: shows
          #strip_dates: yes
    # Mark accepted entries to trakt collection
    trakt_add:
      username: '{{ secrets.trakt.username }}'
      password: '{{ secrets.trakt.password }}'
      list: collection
tasks:
  anime:
    template: anime
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Moar Animu!!
  tv:
    template: tv
    # Notifies using Notify My Android, already paid for premium so not changing.
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: New TV Episode
  search_anime:
    interval: 2 hours
    template: anime
    urlrewrite_search:
      - nyaa:
          filter: trusted only
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Found Animu!
  search_tv:
    interval: 2 hours
    template: tv
    urlrewrite_search:
      - piratebay:
          category: 208
          sort_by: seeds
    notifymyandroid:
      apikey: '{{ secrets.nma_apikey }}'
      event: Found Shows!
  tv_subs:
    template: no_global
    disable: [retry_failed]
    seen: local
    subtitle_queue: emit
    subliminal:
      languages:
        - eng
