# Flexget Configuration File
# http://www.fleget.com
# Created by: Luis Checa <edhaker13@gmail.com>
# Inspired by the cofiguration file from atlanta800's git
# https://github.com/atlanta800/dotfiles/blob/master/flexget/config.yml
# and other examples/information from the wiki
# http://flexget.com/wiki/Plugins

presets:
  global:
    # This preset will be applied to all tasks unless no_global preset is included
    # Make sure there's at least 5GB free space
    free_space:
      path: /srv
      space: 5000
    # Make filename Windows Safe (for samba)
    pathscrub: windows
    # Reject magnets since they don't allow scraping, file size or content filtering
    magnets: no
    # Reject private torrents since I'm not on any private trackers for now
    private_torrents: no
    # Set the quality lower limits by disallowing since fansubs often dont include quality on their release if its 720p
    quality:
      - '!360p'
      - '!480p'
      - '!1080p'
      # 1080p is normally a waste of badwitdh since most realese are hardly good quality 1080p
      # Symbols need to be quoted
    # Set the options of downloaded torrent in deluge
    set:
      # Path results /srv/complete/anime/ShowName/
      movedone: >
        /srv/complete/{{task}}/{{series_name|replace(' ', '')}}
      # Set label to the name of show : fringe, fairy_tail. Makes it manageable
      label: "{{series_name}}"
      # Only download the main file = >90% of total
      main_file_only: yes
       # Output would be -> Show Name 02[720p10bit].mkv
      content_filename: >
        "{{series_name|replace(' ','')}}.{{series_id|pad(2)}}[{{quality|replace(' ','')|replace('unknown','720p')}}]"
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      tokyotosho.info: 6 seconds
      nyaa.eu: 5 seconds
      torrentz.eu: 5 seconds
    # Set api key and app name for NMA http://www.notifymyandroid.com/
    notifymyandroid:
      apikey: aed0c8f91cb1c539f24f900a56c12f07e382710b958a6eec
    # Set the deluge port and auth since i have mine changed
    deluge:
      port: 5555
      
  # This preset has all the anime related settings
  anime:
    # Set to reject or cache entries with only magnets since it can't scrape, file size or content filter it
    magnets: no
    # RSS feeds for anime, ascii force on because of the janapese charactes simetimes cause errors
    inputs:
      # Nyaa shows only english anime and is sorted by seeds
      - rss: { url: 'http://www.nyaa.eu/?page=rss&cats=1_37&filter=1&sort=3', silent: yes, ascii: yes } 
      # Tokyotosho filtered for anime only
      - rss: { url: 'http://tokyotosho.info/rss.php?filter=1', silent: yes, ascii: yes }
    # Set some reasonable size limits also ensures no packs
    content_size:
      max: 800
      min: 50
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
      reject: '*.wmv'
    # Prevent from downloading files that were downloaded manually or are downloading
    exists_series:
      - '/srv/dl/'
      - '/srv/complete/anime/'
    # Filter out any raws, music or manga that may have fallen through the rss filters
    # Case insensitive
    regexp:
      reject: 
        - raw|ost|manga|soundtrack|song|\[ED\]|\[OP\]|(4|7)00(p|x): {from: title} 
    # List of shows I want to see
    series:
      - Bakuman S3
      - BTOOOM
      - CODE Breaker
      - Fairy Tail
      - Girls und Panzer
      # K needs to specify the name in regexp other wise almost anything could come up
      - K:
          name_regexp: (^|\s|「)K(\s|」)
      - Kamisama Kiss
      - Little Busters
      - Magi
      - Onii-chan Dakedo Ai Sae Areba Kankeinai yo ne
      - Psycho Pass
      - Robotics;Notes
      - Shin Sekai Yori
      - Sword Art Online
      - Tonari no Kaibutsu Kun
      - The World God Only Knows
      - Zetsuen no Tempest
  # # Preset for all TV related settings and list of shows, just for show now
  # tv:
    # # Reject rar/packs
    # regexp:
      # reject: 
        # - \.rar|\.r\d\d|password.txt
    # # List of feed to use already filtered to show TV and 720p
    # inputs:
      # - rss: { url: 'http://ezrss.it/search/index.php?&quality=720p&mode=rss', silent: yes }
      # - rss: { url: 'http://rss.bt-chat.com/?group=3', silent: yes }
      # - rss: { url: 'http://kat.ph/tv/?rss=1', silent: yes}
    # # Check for downloaded or downloading
    # exists_series:
      # - '/srv/dl/'
      # - '/srv/complete/TV/'
    # # List of show to watch in case there are some missing from Trakt
    # series:
      # - 2 Broke Girls
      # - Arrow
      # - Alphas
      # - Big Bang Theory
      # - Dexter
      # - Doctor Who
      # - Fringe
      # - Rules of Engament
      # - Supernatural
      # - How I Met Your Mother
tasks:
  anime:
    preset: anime
    notifymyandroid:
      event: Moar Animu!!
  # TV:
    # preset: tv
    # notifymyandroid:
      # event: New TV Episode