# Flexget Configuration File
# http://www.flexget.com
# Created by: Luis Checa <edhaker13@gmail.com>
# Inspired by the configuration file from atlanta800's git
# https://github.com/atlanta800/dotfiles/blob/master/flexget/config.yml
# and other examples/information from the wiki
# http://flexget.com/wiki/Plugins

presets:
# This preset will be applied to all tasks unless no_global preset is included
  global:
    # Make sure there's at least 5GB free space
    free_space:
      path: /media/
      space: 5000
    # Make filename Windows Safe (for samba)
    pathscrub: windows
    # Reject magnets since they don't allow scraping, size or content filtering
    magnets: no
    # Reject private torrents since I'm not on any private trackers for now
    private_torrents: no
    # Some torrents links are invalid https
    verify_ssl_certificates: no
    # Make a rss with successful entries for ease of access
    make_rss:
      file: /home/edhaker13/domains/edhaker.info/public_html/flexget.rss
      days: -1
      items: -1
      encoding: utf-8
    # Make a html file for record keeping
    make_html:
      file: /home/edhaker13/domains/edhaker.info/public_html/flexget.html
    # Notifies me via email, sometime I just forget to check NMA
    email:
      from: flexget@checacorp.com
      to: edhaker13@gmail.com
      template: accepted
      smtp_host: smtp.checacorp.com
      smtp_port: 465
      smtp_ssl: yes
      smtp_username: flexget@checacorp.com
      smtp_password: PQELbr6Arv4gLcdZCFF8
    # Set some reasonable size limits also ensures no packs
    content_size:
      max: 1500
      min: 50
    # Minimum seeds to consider.
    torrent_alive: 10
    # 1080p is a waste of bandwitdh, most releases aren't good quality 1080p
    # But since I'm gonna dl from Home => 720p+
    quality: 720p+
    # Only download mkv or mp4
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
    # Reject common torrent trash
    regexp:
      reject:
        # Block any subbed/dubbed/etc videos
       # - (s|d)ub(s|bed)?\b: {from: title}
        # Block series, only accept one at a time
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        # I don't have any 3D displays
        - \b3-?D\b: {from: title}
        # I've gotten a few trailers that matched as movies. VERY annoying
        - \btrailer\b: {from: title}
        # The following are poor quality types that somehow got through the quality
        - \bR5\b: {from: title}
        # usually due to the title including a keyword like "720p" as well
        - \bWEBSCR\b: {from: title}
        # bad quality sources, just in case
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - \bRAW\b: {from: title}
        # Reject rar/packs/password
        - \.rar|\.r\d\d|password.txt|\.zip
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      tokyotosho.info: 15 seconds
      nyaa.eu: 15 seconds
      kamorra.info: 15 seconds
      feedburner.info: 15 seconds
    # Set api key and app name for NMA http://www.notifymyandroid.com/
    notifymyandroid:
      apikey: aed0c8f91cb1c539f24f900a56c12f07e382710b958a6eec
    # Set download path to rsync from home
    download: /media/torrents/
    # Set the options of downloaded torrent in deluge
    set:
      filename: "{{series_name}}.{{series_id|pad(2)}}[{{quality|replace('unknown','720p')}}].torrent"
    # It was cool to have a seedbox but with no private trackers...
      # Path results /media/anime/ShowName/
      # movedone: >
      #  /media/{{task}}/{{series_name}}
      # Set label to the name of shows : fringe, fairy_tail. Makes it manageable
      # label: "{{series_name}}"
      # Output would be -> Show Name 02[720p10bit].mkv
    # Set the deluge port since I have mine changed.
    #deluge:
      # Only download the main file = >90% of total
      #main_file_only: yes
      #user: deluge
      #pass: deluge
      #port: 5555

  # This preset has all the anime related settings
  anime:
    # Remove score/underscores and multiple spaces
    #manipulate:
    #  - title:
    #      replace:
    #        regexp: '(-|_)'
    #        format: ' '
    #  - title:
    #      replace:
    #        regexp: ' {2,5}'
    #        format: ' '
    # RSS feeds for Anime, force ascii: the japanese characters can cause errors
    inputs:
      # Shows only english anime and is sorted by seeds
      - rss: { url: 'http://www.nyaa.eu/?page=rss&cats=1_37&filter=2', silent: yes, ascii: yes }
      # Filtered for anime only
      #- rss: { url: 'http://tokyotosho.info/rss.php?filter=1', silent: yes, ascii: yes }
    # Prevent from downloading files that are or have been downloaded
    exists_series:
      - '/media/torrents/'
      - '/media/anime/'
    # Filter any raws, OST , manga that may have fallen through the rss filters
    regexp:
      reject:
        -  raw | ost | manga | soundtrack | song |\[ED\]|\[OP\]|(4|7)00(p|x): {from: title}
    # List of shows I want to see, from MAL and manually set
    import_series:
      from:
        myanimelist:
          username: 'edhaker13'
    # Watching again from PC, crunchy is horrible on linux
    series:
      - CODE Breaker:
          name_regexp: C(o|Ø)de( |:) ? Breaker
      - Girls und Panzer
      - Little Busters
      - Magi
      - Maoyuu Maou Yuusha
      - OreShura
      - Psycho Pass
      - Robotics;Notes
      - Sakurasou no Pet na Kanojo
      - Zetsuen no Tempest
  # Preset for all TV related settings and list of shows, just for show now
  tv:
    # List of feeds to use already filtered for shows and 720p
    inputs:
      - rss: { url: 'http://feeds.feedburner.com/dailytvtorrents', silent: yes }
      - rss: { url: 'http://showrss.karmorra.info/rss.php?user_id=118811&hd=null&proper=1', silent: yes }
    # Check for downloaded or downloading
    exists_series:
      - '/media/torrents/'
      - '/media/TV/'
    # List of shows to watch
    import_series:
      from:
        trakt_list:
          username: edhaker13
          api_key: 5da393943021a1fef3c9ea151a4b16fc
          series: watchlist
          strip_dates: yes
    series:
      - 2 Broke Girls
      - Arrow
      - Bones
      - Big Bang Theory
      - Dexter
      - Doctor Who 2005
      - Doctor Who Confidential
      - How I Met Your Mother
      - Supernatural
tasks:
  anime:
    preset: anime
    notifymyandroid:
      event: Moar Animu!!
  TV:
    preset: tv
    notifymyandroid:
      event: New TV Episode
    trakt_acquired:
      username: edhaker13
      password: ARsuIc%'xO-3wO`z7Mk
      api_key: 5da393943021a1fef3c9ea151a4b16fc
      type: series
  search_anime:
    interval: 2 hours
    preset: anime
    urlrewrite_search:
      - nyaa:
          filter: trusted only
    notifymyandroid:
      event: Found Anime!
  search_tv:
    interval: 2 hours
    preset: tv
    urlrewrite_search:
      - piratebay:
          category: 208
          sort_by: seeds
    notifymyandroid:
      event: Found Shows!
